### PR TITLE
CN-193 add return when sql connection returns error

### PR DESCRIPTION
**Pull request by artistico9501**
Not sure if this will fully resolve app crash, but now functionality for registering new clinic and deleting clinic is done successfully without getting '**app crashed**' logs. Problem was that we were getting undefined error for sql connection because after logging error message we don't exit function but continue with execution.

### CODE REVIEW

**Comment by Lazareviceva** [comment]
Please resolve conflicts.

**Review by Lazareviceva — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by Lazareviceva** [comment]
Didn't see that conflicts are resolved, sorry. I will check changes once more and merge them.

**Comment by artistico9501** [comment]
> Resolve conflicts

It was just resolved minute ago

**Review by Lazareviceva — APPROVED** [review]
Everything looks good. Tested, after deleting clinic console is clear, toast message displayed that deletion was succesfull

**Pull request merged**
