### PR TITLE
feat(CN-196/197): confirm message on delete + default name + save draft for sms

### PR DESCRIPTION
**Pull request by INX1**
Deploy:
client

### CODE REVIEW

**Comment by Lazareviceva** [comment]
The changes look good. I need to test it locally and then I will merge it.

**Comment by Lazarevicka** [comment]
Default name doesn't work:

- Create new draft -> Gives some default name
- Click on save changes opens a dialog with input for the name, If you don't enter anything click on the 'Save draft' button will add a draft without a name
- Maybe to put also at input 'Add new SMS draft' or some regex which disables the button if the input is empty

Leaving page doesn't work:
- Create new draft, save changes
- Change the draft that is displayed
- Click on Mailing Email for example
- Dialog 'Your changes won't be saved!' pops up but none change is made on drafts, just switching between them

**Review by Lazareviceva — CHANGES_REQUESTED** [review]
Default name doesn't work:

- Create new draft -> Gives some default name
- Click on save changes opens a dialog with input for the name, If you don't enter anything click on the 'Save draft' button will add a draft without a name
- Maybe to put also at input 'Add new SMS draft' or some regex which disables the button if the input is empty

Leaving page doesn't work:
- Create new draft, save changes
- Change the draft that is displayed
- Click on Mailing Email for example
- Dialog 'Your changes won't be saved!' pops up but none change is made on drafts, just switching between them

**Comment by INX1** [comment]
I added default message, but name depends on translations
Other stuff also fixed

**Review by Lazareviceva — APPROVED** [review]

**Pull request merged**
