### PR TITLE
Cn 194/handle invalid datetime field

### PR DESCRIPTION
**Pull request by artistico9501**
Please check attachment **CN 194 testing use cases.pdf** in story https://clinicnodedev.atlassian.net/browse/CN-194 to see how to reproduce use cases for testing.

### CODE REVIEW

**Comment by artistico9501** [comment]
Moving PR to draft since I found one more place I have to fix invalid date.

**Review by koja5 — COMMENTED** [review]
For now, everything looks fine. Just need to check how datepickers look in other components and maybe need to make some global functions to validate DateTime value for each component.
image

**Comment by artistico9501** [comment]
I also did search for all places where kendo-datepicker was used and based on that is created pdf with all test cases. When it comes to global validation, not sure how it will work with this component from external library  but maybe good option would be to create wrapper component where we can implement date validation.

**Comment by koja5** [comment]
It will be good. 
Evaluate what is best to do now.

**Review by koja5 — CHANGES_REQUESTED** [review]
We have some conflict in two components. Please check.

**Comment by artistico9501** [comment]
> conflict

Resolved

**Review by koja5 — APPROVED** [review]

**Pull request merged**
